### ISSUE TITLE
Blocks don't show in edit page view

### ISSUE THREAD

**Issue by RomanGru** [sheadawson/silverstripe-blocks#127]
I have installed Blocks successfully, but Blocks are only displayed in the admin-sidebar, but not in the page-edit view, as you can see in the screenshots.. I followed the installationinstructions and edit the _config.yml and so on. What went wrong, that I can't see Blocks in the admin page-edit page?
Thank you for your answer

**Comment by Doniz** [comment]
Are you sure that you set you theme? and that theme are active?

```yaml
BlockManager:
  themes:
    yourThemeName:
      areas:
        BeforeContent: true
        AfterContent: true
      disabled_blocks:
        - BaseBlock
        - ContentBlock
```

**Comment by RomanGru** [comment]
You mean, defined in the yml? 

but the theme name isn't mentioned in the example yml 
"SheaDawson\Blocks\BlockManager:
	areas:
		Sidebar: true
		BeforeContent:
			only: HomePage 
			except: HomePage 
		Footer: true "

I tried your version, but it didn't worked as well. (I used of course my Theme and adjust it). I installed silverstripe some days ago with composer, so it should be the latest version.

**Comment by Doniz** [comment]
on the SilverStriep 3.x versions working well. But the very last SilverStripe version 4 and greater are a bit buggy. I tried right now. So the first issue was `SilverStripe\Object\Object` which are not existing at latest version, it's should be use `SilverStripe\View\ViewableData` instead at `BlockManager` extendable class. Second one i try to copy whole content from https://github.com/sheadawson/silverstripe-blocks#1-define-block-areas-and-settings-for-your-project-in-mysite_configconfigyml so i get an error for space indents. And it should look like this:

```yaml
SheaDawson\Blocks\BlockManager:
  areas:
    Sidebar: true # a Sidebar area will be available on all page types
    BeforeContent:
        only: HomePage # a BeforeContent area will be available only on HomePage page types
    AfterContent:
        except: HomePage # a AfterContent area will be available on all page types except HomePage
    Footer: true # a Footer area will be available on all page types
#  options:
    #use_blocksets: false # Whether to use BlockSet functionality (default if undeclared: true)
    #use_extra_css_classes: true # Whether to allow cms users to add extra css classes to blocks (default if undeclared: false)
    #prefix_default_css_classes: 'myprefix--' # prefix the automatically generated CSSClasses based on class name (default if undeclared: false)
    #pagetype_whitelist: # Enable the Blocks tab only pages of these types (optional)
    #  - HomePage
    #pagetype_blacklist: # Disable the Blocks tab on pages of these types (optional)
    #  - ContactPage
    #disabled_blocks: #allows you to disable specific blocks (optional)
    #  - ContentBlock
    #use_default_blocks: false # Disable/enable the default Block types (ContentBlock) (default if undeclared: true)
    #block_area_preview: false # Disable block area preview button in CMS (default if undeclared: true)
```

without tabular of spaces. And i see it's working:

![](https://i.gyazo.com/ba78ae91e056509409445b8b7bac5eec.png). 

I would rather using 3.x version of SilverStripe, because the latest one not supporting some of the modules, and it's not stable yet.

**Comment by Doniz** [comment]
i read one more time your questions. 

> but Blocks are only displayed in the admin-sidebar, but not in the page-edit view

so you also seeing the same window where i post it ? if you trying to see the areas of the blocks where it should be included, you should define areas in the yaml file: 

```yaml
SheaDawson\Blocks\BlockManager:
  areas:
    Sidebar: true # a Sidebar area will be available on all page types
    BeforeContent:
        only: HomePage # a BeforeContent area will be available only on HomePage page types
    AfterContent:
        except: HomePage # a AfterContent area will be available on all page types except HomePage
    Footer: true # a Footer area will be available on all page types
```

as you did it already. So those areas also set to the Page.ss as example:

```html
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
    <% include Header %>

    $BlockArea('BeforeContent')
    $Layout
    $BlockArea('AfterContent')
</div>
```
