### ISSUE TITLE
Support for Theme-less sites

### ISSUE THREAD

**Issue by jonom** [sheadawson/silverstripe-blocks#29]
Hi Shea,

I recently stopped using the `themes` folder in SilverStripe development because I've only ever built one website where I actually needed it (a subsites website). I now put everything in the `mysite` folder which keeps all my custom code nicely contained in one folder.

I tried to use this module today for a site but I'm coming up a bit short - it looks like it won't work at all if you're not using the `themes` folder?

Can I suggest that this module allows some default/theme-independant settings which can then be overidden at the theme level? Could maybe look like this:

```yml
BlockManager:
  areas:
    Sidebar: false # default/theme-less setting
  themes:
    simple:
      areas:
        Sidebar: true # overridden for Simple theme
```

**Comment by jonom** [comment]
Here's a hacky but simple solution:

```php
	/*
	 * Get the current/active theme or 'default' to support theme-less sites
	 */
	private function getTheme(){
		$currentTheme = Config::inst()->get('SSViewer', 'theme');
		return $currentTheme ? $currentTheme : 'default';
	}
```

```yml
BlockManager:
  themes:
    default:
      areas:
        Sidebar: false
```
