### ISSUE TITLE
Missing add button

### ISSUE THREAD

**Issue by asecondwill** [sheadawson/silverstripe-blocks#67]
Hello.  

I can't get the Add button to display in the edit page.  

I've installed the module through composer, copied the sample YAML, added the snippet to my template (and checked it by clicking the preview).  Iv'e flushed 1'd and dev/builded my little heart out.  No add button. 

Any gentle kicks towards figuring out what i have done wrong?

**Comment by asecondwill** [comment]
composer.json bits for ref

````
    "silverstripe/cms": "3.1.*@stable",
    "silverstripe/framework": "3.1.*@stable",
     "sheadawson/silverstripe-blocks" : "1.0.8"

````

**Comment by sheadawson** [comment]
Hi Will,

I've just tested and seems to be working for me, with those same cms/framework versions. 

Is this the view where you are not seeing an add button? Got a screenshot? Can you paste in your block yml config. 

![screen shot 2016-03-07 at 9 29 01 am](https://cloud.githubusercontent.com/assets/1166136/13556779/1f27416a-e447-11e5-9bbf-45e2abd8e72e.png)

**Comment by digitall-it** [comment]
I got the same problem, installed twice to test it. Here's my `composer.json`

```
{
    "name": "silverstripe/installer",
    "description": "The SilverStripe Framework Installer",
    "require": {
        "php": ">=5.3.3",
        "silverstripe/cms": "3.4.1",
        "silverstripe/framework": "3.4.1",
        "silverstripe/reports": "3.4.1",
        "silverstripe/siteconfig": "3.4.1",
        "sheadawson/silverstripe-blocks": "^1.1",
        "unisolutions/silverstripe-copybutton": "^1.0",
        "micschk/silverstripe-gridfieldsitetreebuttons": "^1.0",
        "micschk/silverstripe-excludechildren": "^1.1"
    },
    "require-dev": {
        "phpunit/PHPUnit": "~3.7@stable",
        "oddnoc/silverstripe-artefactcleaner": "^3.0"
    },
    "config": {
        "process-timeout": 600
    },
    "prefer-stable": true,
    "minimum-stability": "dev"
}
```

![screenshot 2016-11-04 alle 01 50 51](https://cloud.githubusercontent.com/assets/3578378/19990837/2968d708-a231-11e6-9c2a-24039cc35315.jpg)

**Comment by sheadawson** [comment]
Can you paste you yml config here, that's probably where the misconfiguration is, if it's a miconfiguration problem

**Comment by digitall-it** [comment]
```
---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'simple'
BlockManager:
    themes:
        simple:
            areas:
                Sidebar: true # a Sidebar area will be available on all page types in simple theme
                BeforeContentA:
                    only: HomePage # a BeforeContent area will be available only on HomePage page types in simple theme
                AfterContentB:
                    except: HomePage # a AfterContent area will be available on all page types except HomePage in simple theme
                Footer: true # a Footer area will be available on all page types in simple theme

            use_blocksets: true # Whether to use BlockSet functionality (default if undeclared: true)
            use_extra_css_classes: true # Whether to allow cms users to add extra css classes to blocks (default if undeclared: false)
            prefix_default_css_classes: 'myprefix--' # prefix the automatically generated CSSClasses based on class name (default if undeclared: false)
            #pagetype_whitelist: # Enable the Blocks tab only pages of these types (optional)
            #  - HomePage
            #pagetype_blacklist: # Disable the Blocks tab on pages of these types (optional)
            #  - ContactPage
            #disabled_blocks: #allows you to disable specific blocks (optional)
            #  - ContentBlock
    use_default_blocks: true # Disable/enable the default Block types (ContentBlock) (default if undeclared: true)
    block_area_preview: true # Disable block area preview button in CMS (default if undeclared: true)
```
