### ISSUE TITLE
Can't add blocks (on page or blocks admin

### ISSUE THREAD

**Issue by leomeloxp** [sheadawson/silverstripe-blocks#95]
Hi, I have a new setup using your module and can't see the add block buttons. I've seen there was a similar issue here before but it was never confirmed solved (or bug).

I'm not sure how to debug this so any guidance would be appreciated. Here's all the info I think could be relevant, please let me know if I can be of any more assitance ✌️

*config.yml* 
```yml
# Blog manager
BlockManager:
  themes:
    themename:
      areas:
        AfterContent: true
      use_blocksets: true
      use_extra_css_classes: true 
  use_default_blocks: false
```

*composer.json*
```json

"require": {
		"php": ">=5.3.4",
		"silverstripe/cms": "3.3.1",
		"silverstripe/framework": "3.3.1",
		"silverstripe/siteconfig": "3.3.1",
		"silverstripe-australia/gridfieldextensions": "~1.1",
		"quadra-digital/silverstripe-card-layout": "dev-develop",
		"quadra-digital/silverstripe-sonos": "dev-develop",
		"silverstripe/userforms": "^3.1",
		"sheadawson/silverstripe-blocks": "^1.0"
	},
	"require-dev": {
		"phpunit/PHPUnit": "~3.7"
	},
	"extra": {
		"branch-alias": {
			"3.x-dev": "3.3.x-dev"
		}
	},
	"config": {
		"process-timeout": 600
	},
	"prefer-stable": true,
	"minimum-stability": "dev"
}
```

```
PHP 5.6.16 (cli) (built: Nov 27 2015 20:51:53)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
```

![screen shot 2016-05-23 at 11 55 24](https://cloud.githubusercontent.com/assets/266852/15468662/5b15dede-20dd-11e6-8b4d-b4f9ef1abbf8.png)
![screen shot 2016-05-23 at 11 55 50](https://cloud.githubusercontent.com/assets/266852/15468661/5b1370d6-20dd-11e6-9cea-93bed41f87e2.png)
